export const elements = {
  loadingSpinnerOverlay: document.getElementById("loading-spinner-overlay"),
  btnToggleSidebar: document.getElementById("btnToggleSidebar"),
  modalOverlay: document.getElementById("modalOverlay"),
  bodyEl: document.body,
  prevMonthBtn: document.getElementById("prevMonthBtn"),
  nextMonthBtn: document.getElementById("nextMonthBtn"),
  monthPicker: document.getElementById("monthPicker"),
  btnQuickAddOrdinary: document.getElementById("btnQuickAddOrdinary"),
  btnGoToToday: document.getElementById("btnGoToToday"),
  btnDownloadPDF: document.getElementById("btnDownloadPDF"),
  btnFecharTodosOrcamentos: document.getElementById("btnFecharTodosOrcamentos"),
  currentMonthDisplay: document.getElementById("currentMonthDisplay"),
  totalReceitasDisplay: document.getElementById("totalReceitas"),
  totalDespesasDisplay: document.getElementById("totalDespesas"),
  saldoMesDisplay: document.getElementById("saldoMes"),
  listaTransacoesUl: document.getElementById("listaTransacoes"),
  searchInput: document.getElementById("searchInput"),
  clearSearchBtn: document.getElementById("clearSearchBtn"),
  btnDeepSearch: document.getElementById("btnDeepSearch"),
  modalDetalhesSerie: document.getElementById("modalDetalhesSerie"),
  modalDetalhesSerieTitulo: document.getElementById("modalDetalhesSerieTitulo"),
  listaDetalhesSerieUl: document.getElementById("listaDetalhesSerie"),
  btnDespesasTerceiros: document.getElementById("btnDespesasTerceiros"),
  modalMenuTerceiros: document.getElementById("modalMenuTerceiros"),
  modalConsultarTerceiros: document.getElementById("modalConsultarTerceiros"),
  btnAbrirCadastroTerceiros: document.getElementById(
    "btnAbrirCadastroTerceiros",
  ),
  btnAbrirConsultaTerceiros: document.getElementById(
    "btnAbrirConsultaTerceiros",
  ),
  listaDividasTerceirosUl: document.getElementById("listaDividasTerceiros"),
  // ADICIONADO:
  terceirosTitulo: document.getElementById("terceirosTitulo"),
  resumoDividasTerceiros: document.getElementById("resumoDividasTerceiros"),
  btnTerceirosAnterior: document.getElementById("btnTerceirosAnterior"),
  btnTerceirosProximo: document.getElementById("btnTerceirosProximo"),
  modalEditarDivida: document.getElementById("modalEditarDivida"),
  modalEditarDividaTitulo: document.getElementById("modalEditarDividaTitulo"),
  dividaEditIdInput: document.getElementById("dividaEditId"),
  dividaEditSerieIdInput: document.getElementById("dividaEditSerieId"),
  dividaEditContextoInput: document.getElementById("dividaEditContexto"),
  nomeDividaEditInput: document.getElementById("nomeDividaEdit"),
  valorDividaEditInput: document.getElementById("valorDividaEdit"),
  btnCancelarEdicaoDivida: document.getElementById("btnCancelarEdicaoDivida"),
  btnSalvarEdicaoDivida: document.getElementById("btnSalvarEdicaoDivida"),
  modalCadastrarPessoa: document.getElementById("modalCadastrarPessoa"),
  nomePessoaInputModal: document.getElementById("nomePessoaInputModal"),
  btnSalvarPessoaModal: document.getElementById("btnSalvarPessoaModal"),
  modalNovaTransacao: document.getElementById("modalNovaTransacao"),
  btnAbrirModalNovaTransacao: document.getElementById("btnNovaTransacao"),
  tipoTransacaoSelect: document.getElementById("tipoTransacao"),
  nomeTransacaoInput: document.getElementById("nomeTransacao"),
  btnSalvarTransacao: document.getElementById("btnSalvarTransacao"),
  modalHeaderNovaTransacao: document.getElementById("modalNovaTransacaoTitulo"),

  // Containers de Seção (Cascata)
  blocoPessoaTerceiros: document.getElementById("blocoPessoaTerceiros"),
  pessoaSelect: document.getElementById("pessoaSelect"),
  secaoReceita: document.getElementById("secaoReceita"),
  secaoCategoriaDespesa: document.getElementById("secaoCategoriaDespesa"),
  secaoDespesaOrdinaria: document.getElementById("secaoDespesaOrdinaria"),
  secaoDespesaCartao: document.getElementById("secaoDespesaCartao"),
  secaoPatrimonio: document.getElementById("secaoPatrimonio"),

  // Campos de Patrimônio
  subTipoPatrimonio: document.getElementById("subTipoPatrimonio"),
  frequenciaPatrimonio: document.getElementById("frequenciaPatrimonio"),
  containerTipoCadastroPatrimonio: document.getElementById(
    "containerTipoCadastroPatrimonio",
  ),
  tipoCadastroParcelaPatrimonio: document.getElementById(
    "tipoCadastroParcelaPatrimonio",
  ),
  camposParceladoPatrimonio: document.getElementById(
    "camposParceladoPatrimonio",
  ),
  qtdParcelasPatrimonio: document.getElementById("qtdParcelasPatrimonio"),
  parcelaAtualPatrimonio: document.getElementById("parcelaAtualPatrimonio"),
  valorPatrimonio: document.getElementById("valorPatrimonio"),
  dataPatrimonio: document.getElementById("dataPatrimonio"),

  // Campos de Receita
  valorReceita: document.getElementById("valorReceita"),
  dataEntradaReceita: document.getElementById("dataEntradaReceita"),
  frequenciaReceita: document.getElementById("frequenciaReceita"),

  // Campos de Despesa Comuns
  categoriaDespesa: document.getElementById("categoriaDespesa"),

  // Campos de Despesa Ordinária
  frequenciaDespesaOrd: document.getElementById("frequenciaDespesaOrd"),
  valorDespesaOrd: document.getElementById("valorDespesaOrd"),
  dataVencimentoDespesaOrd: document.getElementById("dataVencimentoDespesaOrd"),
  camposParceladaOrd: document.getElementById("camposParceladaOrd"),
  containerTipoCadastroOrd: document.getElementById("containerTipoCadastroOrd"),
  tipoCadastroParcelaOrd: document.getElementById("tipoCadastroParcelaOrd"),
  qtdParcelasOrd: document.getElementById("qtdParcelasOrd"),
  parcelaAtualOrd: document.getElementById("parcelaAtualOrd"),

  // Campos de Despesa Cartão
  cartaoDespesa: document.getElementById("cartaoDespesa"),
  orcamentoVinculado: document.getElementById("orcamentoVinculado"),
  containerOrcamentoVinculado: document.getElementById(
    "containerOrcamentoVinculado",
  ),
  frequenciaDespesaCartao: document.getElementById("frequenciaDespesaCartao"),
  containerTipoCadastroCartao: document.getElementById(
    "containerTipoCadastroCartao",
  ),
  valorDespesaCartao: document.getElementById("valorDespesaCartao"),
  camposParcelamentoCartao: document.getElementById("camposParcelamentoCartao"),
  tipoCadastroParcelaCartao: document.getElementById(
    "tipoCadastroParcelaCartao",
  ),
  qtdParcelasCartao: document.getElementById("qtdParcelasCartao"),
  parcelaAtualCartao: document.getElementById("parcelaAtualCartao"),
  btnGerenciarCartoes: document.getElementById("btnGerenciarCartoes"),
  modalGerenciarCartoes: document.getElementById("modalGerenciarCartoes"),
  btnAbrirModalCadastroCartao: document.getElementById(
    "btnAbrirModalCadastroCartao",
  ),
  listaCartoesCadastradosUl: document.getElementById("listaCartoesCadastrados"),
  btnMenuOrcamentos: document.getElementById("btnMenuOrcamentos"),
  modalCadastrarCartao: document.getElementById("modalCadastrarCartao"),
  modalCartaoTitulo: document.getElementById("modalCartaoTitulo"),
  nomeCartaoInputModal: document.getElementById("nomeCartao"),
  diaVencimentoFaturaInputModal: document.getElementById("diaVencimentoFatura"),
  btnSalvarCartaoModalBtn: document.getElementById("btnSalvarCartaoModal"),
  cartaoEditIdInput: document.getElementById("cartaoEditId"),
  modalDetalhesFaturaCartao: document.getElementById(
    "modalDetalhesFaturaCartao",
  ),
  faturaCartaoNomeTitulo: document.getElementById("faturaCartaoNomeTitulo"),
  faturaCartaoTotalValor: document.getElementById("faturaCartaoTotalValor"),
  faturaCartaoDataVencimento: document.getElementById(
    "faturaCartaoDataVencimento",
  ),
  listaComprasFaturaCartaoUl: document.getElementById(
    "listaComprasFaturaCartao",
  ),
  btnAddDespesaFromFatura: document.getElementById("btnAddDespesaFromFatura"),
  btnAjustesFatura: document.getElementById("btnAjustesFatura"),
  btnFaturaAnterior: document.getElementById("btnFaturaAnterior"),
  btnFaturaProxima: document.getElementById("btnFaturaProxima"),
  quickAddFeedback: document.getElementById("quickAddFeedback"),
  modalOrcamentos: document.getElementById("modalOrcamentos"),
  modalOrcamentoTitulo: document.getElementById("modalOrcamentoTitulo"),
  btnAbrirModalCadastroOrcamento: document.getElementById(
    "btnAbrirModalCadastroOrcamento",
  ),
  modalCadastrarOrcamento: document.getElementById("modalCadastrarOrcamento"),
  modalFormOrcamentoTitulo: document.getElementById("modalFormOrcamentoTitulo"),
  orcamentoEditIdInput: document.getElementById("orcamentoEditId"),
  nomeOrcamentoInput: document.getElementById("nomeOrcamento"),
  valorOrcamentoInput: document.getElementById("valorOrcamento"),
  diaOrcamentoInput: document.getElementById("diaOrcamento"),
  btnSalvarOrcamento: document.getElementById("btnSalvarOrcamento"),
  listaOrcamentosUl: document.getElementById("listaOrcamentos"),
  modalDetalhesOrcamento: document.getElementById("modalDetalhesOrcamento"),
  orcamentoDetalhesTitulo: document.getElementById("orcamentoDetalhesTitulo"),
  orcamentoDetalhesTotal: document.getElementById("orcamentoDetalhesTotal"),
  orcamentoDetalhesGasto: document.getElementById("orcamentoDetalhesGasto"),
  orcamentoDetalhesRestante: document.getElementById(
    "orcamentoDetalhesRestante",
  ),
  listaGastosOrcamento: document.getElementById("listaGastosOrcamento"),
  modalAjustesFatura: document.getElementById("modalAjustesFatura"),
  modalAjustesFaturaTitulo: document.getElementById("modalAjustesFaturaTitulo"),
  descricaoAjusteInput: document.getElementById("descricaoAjuste"),
  valorAjusteInput: document.getElementById("valorAjuste"),
  btnSalvarAjuste: document.getElementById("btnSalvarAjuste"),
  listaAjustesFaturaUl: document.getElementById("listaAjustesFatura"),
  totalAjustesValorSpan: document.getElementById("totalAjustesValor"),
  modalConfirmarAcaoSerie: document.getElementById("modalConfirmarAcaoSerie"),
  modalConfirmarAcaoSerieTitulo: document.getElementById(
    "modalConfirmarAcaoSerieTitulo",
  ),
  modalConfirmarAcaoSerieTexto: document.getElementById(
    "modalConfirmarAcaoSerieTexto",
  ),
  btnAcaoSerieApenasEsta: document.getElementById("btnAcaoSerieApenasEsta"),
  btnAcaoSerieToda: document.getElementById("btnAcaoSerieToda"),
  btnRelatorios: document.getElementById("btnRelatorios"),
  modalRelatorios: document.getElementById("modalRelatorios"),
  relatorioTitulo: document.getElementById("relatorioTitulo"),
  relatorioCorpo: document.getElementById("relatorioCorpo"),
  btnRelatorioAnterior: document.getElementById("btnRelatorioAnterior"),
  btnRelatorioProximo: document.getElementById("btnRelatorioProximo"),
  modalDetalhesFiltroRelatorio: document.getElementById(
    "modalDetalhesFiltroRelatorio",
  ),
  detalhesFiltroRelatorioTitulo: document.getElementById(
    "detalhesFiltroRelatorioTitulo",
  ),
  listaDetalhesFiltroRelatorioUl: document.getElementById(
    "listaDetalhesFiltroRelatorio",
  ),
  modalAuth: document.getElementById("modalAuth"),
  modalAuthTitulo: document.getElementById("modalAuthTitulo"),
  authFeedback: document.getElementById("authFeedback"),
  emailInput: document.getElementById("emailInput"),
  passwordInput: document.getElementById("passwordInput"),
  btnAuthAction: document.getElementById("btnAuthAction"),
  btnToggleAuthMode: document.getElementById("btnToggleAuthMode"),
  btnLogout: document.getElementById("btnLogout"),
  sidebarFooter: document.querySelector(".sidebar-footer"),
  lastUpdatedDisplay: document.getElementById("lastUpdatedDisplay"),
  btnToggleVisibility: document.getElementById("btnToggleVisibility"),
  btnResendVerification: document.getElementById("btnResendVerification"),
  btnSairAuth: document.getElementById("btnSairAuth"),
  // ... (mantenha os outros)
  btnAbrirConsultaPessoas: document.getElementById("btnAbrirConsultaPessoas"),
  modalGerenciarPessoas: document.getElementById("modalGerenciarPessoas"),
  listaPessoasCadastradasUl: document.getElementById("listaPessoasCadastradas"),
  btnAbrirModalCadastroPessoaDirect: document.getElementById(
    "btnAbrirModalCadastroPessoaDirect",
  ),
  modalConfirmarExclusaoCartao: document.getElementById(
    "modalConfirmarExclusaoCartao",
  ),
  infoUltimaCompraCartao: document.getElementById("infoUltimaCompraCartao"),
  dataCorteExclusaoCartao: document.getElementById("dataCorteExclusaoCartao"),

  btnConfirmarSoftDeleteCartao: document.getElementById(
    "btnConfirmarSoftDeleteCartao",
  ),
  auditMinhasCompras: document.getElementById("auditMinhasCompras"),
  auditTerceiros: document.getElementById("auditTerceiros"),
  auditTotalEsperado: document.getElementById("auditTotalEsperado"),
  inputValorBanco: document.getElementById("inputValorBanco"),
  resultadoDiferenca: document.getElementById("resultadoDiferenca"),
  faturaCartaoTotalValor: document.getElementById("faturaCartaoTotalValor"),
  checkFaturaConferida: document.getElementById("checkFaturaConferida"),
  modalConfirmarEscopoOrcamento: document.getElementById(
    "modalConfirmarEscopoOrcamento",
  ),
  btnOrcamentoApenasEste: document.getElementById("btnOrcamentoApenasEste"),
  btnOrcamentoEsteEFuturos: document.getElementById("btnOrcamentoEsteEFuturos"),
  btnOrcamentoCancelar: document.getElementById("btnOrcamentoCancelar"),
  modalConfirmarExclusaoEscopoOrcamento: document.getElementById(
    "modalConfirmarExclusaoEscopoOrcamento",
  ),
  btnExcluirOrcamentoApenasEste: document.getElementById(
    "btnExcluirOrcamentoApenasEste",
  ),
  btnExcluirOrcamentoEsteEFuturos: document.getElementById(
    "btnExcluirOrcamentoEsteEFuturos",
  ),
  btnExcluirOrcamentoCancelar: document.getElementById(
    "btnExcluirOrcamentoCancelar",
  ),
  userEmailDisplay: document.getElementById("userEmailDisplay"),
  // =========================================
  //        ELEMENTOS DO WEEKLY TRACKER
  // =========================================
  btnWeeklyTracker: document.getElementById("btnWeeklyTracker"),
  modalWeeklyTracker: document.getElementById("modalWeeklyTracker"),
  weeklyTrackerTitulo: document.getElementById("weeklyTrackerTitulo"),
  btnAbrirNovoCiclo: document.getElementById("btnAbrirNovoCiclo"),
  trackerTabsContainer: document.getElementById("trackerTabsContainer"),
  containerCiclosTracker: document.getElementById("containerCiclosTracker"),

  // Modal de Configuração de Ciclo
  modalConfigCiclo: document.getElementById("modalConfigCiclo"),
  modalConfigCicloTitulo: document.getElementById("modalConfigCicloTitulo"),
  cicloEditIdInput: document.getElementById("cicloEditId"),
  dataInicioCicloInput: document.getElementById("dataInicioCiclo"),
  dataFimCicloInput: document.getElementById("dataFimCiclo"),
  metaCicloInput: document.getElementById("metaCiclo"),
  btnSalvarConfigCiclo: document.getElementById("btnSalvarConfigCiclo"),

  // Modal de Valor Inicial
  modalValorInicialCiclo: document.getElementById("modalValorInicialCiclo"),
  cicloValorInicialIdInput: document.getElementById("cicloValorInicialId"),
  valorInicialCicloInput: document.getElementById("valorInicialCicloInput"),
  btnSalvarValorInicial: document.getElementById("btnSalvarValorInicial"),
};
