export const state = {
  currentDate: new Date(),
  reportDate: new Date(),
  userAguardandoVerificacao: null,
  isDuringRegistration: false,
  transacoes: [],
  cartoes: [],
  ajustesFatura: [],
  orcamentos: [],
  orcamentosFechados: [],
  dividasTerceiros: [],
  pessoas: [],
  currentFaturaDate: null,
  dividasTerceirosDate: new Date(),
  currentModalStep: 1,
  isEditMode: false,
  editingTransactionId: null,
  editingSerieId: null,
  isCartaoEditMode: false,
  isQuickAddMode: false,
  isModoTerceiros: false,
  isRegisterMode: false,
  currentUser: null,
  openModals: [],
  areValuesHidden: false,
  // NOVAS VARIÁVEIS:
  isPessoaEditMode: false,
  editingPessoaId: null,
};
